### Main App parameters ###
APP_HEIGHT = 300
APP_WIDTH = 900

ICON_FILEPATH = 'assets/satellite.ico'

HOUSEKEEPING_DATA_FOLDER_FILEPATH = 'housekeeping_data'
HOUSEKEEPING_DATA_FILE_PREFIX = 'hk_logs_'

APP_DOWNLINK_PROCESS_CHECK_INTERVAL = 30000
