##### CCSDS TELEMETRY CONSTANTS #####
CCSDS_BEACON_LEN_BYTES = 38

CCSDS_OBC_HK_DATAPOINT_LEN_BYTES = 11
CCSDS_OBC_HK_DATAPOINT_COUNT = 15
CCSDS_OBC_TELEMETRY_LEN_BYTES = 172

TELECOMMAND_TYPE_OBC_HK_REQUEST = 1
TELECOMMAND_TYPE_PAYLOAD_HK_REQUEST = 5
TELECOMMAND_TYPE_MISSION_DOWNLINK = 11

TELECOMMAND_PACKET_LEN_BYTES = 24
